# adventure game
import time
print('Welcome to the Santa Cruz Mountain Adventure Game!')
print('**************************************')
print('You are visiting Santa Cruz, California.')
print('You go on an evening adventure in the mountains.')
print('It is dark.')
print('You can pick one item to take with you -  ')
print('map, flashlight, cheeseburger, rope, batteries, or gokart: ')
item = input('What do you choose?: ')
print('You hear a loud humming noise. It gets even louder! You are scared.')
choice1 = input('Do you follow the sound? Enter yes or no: ')
if choice1 == 'yes':
    print('After all, this is an adventure. You\'ll be fine.')
    print('A nagging voice in your head disagrees.')
    print('Too late to change now.')
    if item == 'gokart' or 'batteries':
        print('You warily inch toward the sound.')
    else:
        print('You slowly inch closer to the sound, holding your', item, 'out like a weapon.')
    print('The sound suddenly stops. Something is wrong here.')
    print('You look for the starting point.')
    print('...')
    print('Where is it?')
    print('You are now LOST ... ')
    print('You try to call on your phone, but there is no signal.')
    print('Aimlessly, you walk around.')
    print('Suddenly, the sound starts up again!')
    print('You run away quickly!')
    print('You are running fast. The sound gets really loud!')
    print('Panting, you duck behind a tree and the sound stops.')
    print('You have to get out of here!')
else:
    print('You won\'t follow it.')
    print('You\'re not taking risks.')
    print('You want to go home.')
    print('You walk to the starting point.')
    print('Huh?')
    print('Where is the starting point?')
    print('You realize that you are LOST ... ')
    print('You try to call on your phone, but there is no signal.')
    print('You walk around aimlessly.')
    print('All of a sudden you hear the sound again.')
    print('You can\'t give up now.')
    print('So you run away fast.')
    print('You hide in a bush, exhausted.')
    print('The sound stops.')
    print('You have to get out of here!')
direction = input('Which direction do you go? north, south, east, or west?: ')
if direction == 'north':
    print('You reach an abandoned cabin.')
    if item == 'map':
        print('You use the map to find your way back home from the cabin.')
        print('You win the game!')
        print('But it seems there could be more to your adventure.')
        print('You can try again...')
    elif item == 'gokart':
        print('Here is a good place to rest.')
        print('If only you had food...')
        print('You rest for an hour here.')
        print('Now you are ready to go.')
        print('You use your gokart to drive down a big hill.')
        print('After a few more minutes of travel, you come to an empty gas station.')
        print('You stick out your thumb for a lift.')
        print('After a while, a bus spewing gas comes to the station.')
        print('You pump your fist!')
        print('But...')
        trust = input('Will you trust him?: ')
        if trust == 'yes':
            print('You ask if you can get a ride.')
            print('The driver says sure.')
            print('"Where do you want to go?", he asks.')
            print('You tell him your address.')
            print('He asks you if you\'re hungry.')
            print('You realize you haven\'t ate in hours.')
            print('He asks where you want to go to eat.')
            fav_restaurant = input('Enter your favorite restaurant: ')
            print('He takes you to', fav_restaurant, 'and you order a ton of food and gobble it up.')
            print('You thank him a lot and he takes you home.')
            print('You have won the game!')
        elif trust == 'no':
            print('You won\'t trust him.')
            print('He does look kind of shady.')
            print('He drives by.')
            print('You wait...')
            print('...')
            print('...')
            print('Suddenly, you see a flying minivan arc though the air!')
            print('You are at a loss for words.')
            print('The minivan is beat up and has poorly drawn flames on the side, but there are propellers where the wheels are supposed to be.')
            print('It crash lands, hitting a gas pump and a gas can.')
            print('They fly through the air(bump, bump, bump, bump, KABOOM!)')
            print('There is a huge explosion, and the mininvan lands next to you.')
            print('A woman gets out.')
            print('"Sorry about that.", she says.')
            print('You manage to gasp out, "Who are you?"')
            print('She introduces herself as just Melinda. She doesn\'t give a last name.')
            print('"This is a flying car I made.", she continues.')
            print('"I was driving to the Guiness World Records Office to show them I made a flying car.", she explains.')
            print('"But I saw you and you look like you need a lift."')
            print('You gape at her in disbelief.')
            print('"Oh, the flames? My kids painted those."')
            print('"Me and my husband have a company called Cars of the Future."')
            print('She hands you a business card. It reads, Cars of the Future in a flaming font.')
            print('She asks where you want to go.')
            print('You tell her your address.')
            print('You fly there, people marveling at the minivan.')
            print('"T-thanks.", you tell her.')
            print('"No problem.", she says.')
            print('She flies off.')
            print('You have won the game!')
    else:
            print('If you had a map, you could find your way. If you had a gokart, you could have rode home without getting tired.')
            print('You lost the game.')
            print('Try again...')
elif direction == 'south':
    print('You come to a river with a broken bridge.')
    print('How could this be fixed...?')
    if item == 'map', 'flashlight', 'cheeseburger', 'batteries', or 'gokart':
        print('You have nothing that can help you fix the bridge, so you walk as far as you can.')
        print('Nowhere to go...')
        print('You have lost the game.')
    else:
        print('Oh yeah, you have a rope.')
        print('You can fix the bridge.')
        print('After working for a while, you fix the bridge.')
        print('You walk across...')
        print('Almost there...')
        print('Suddenly, a purple bus appears out of nowhere.')
        print('Graffiti on the side of it identifies it as "The Knight Bus"')
        print('It rumbles by, rocking from side to side dangerously.')
        print('You realize it\'s coming toward you!')
        print('You run back where you came as fast as you can.')
        print('It\'s coming closer!')
        print('Suddenly, it disappears. You hear glass shattering and a cat meowing.')
        print('That was crazy!')
        print('You pick yourself up and keep on going.')
        print('Soon, you come to the town
        
            
            
            
        

    
       
       
      
