bill_total = input('What is the total on the bill?: ')
tip_percent = input('What percent tip would you like to give?: ')
sharing_number = input('How many people are sharing the bill?: ')
bill_total = int(bill_total)
tip_percent = int(tip_percent)
sharing_number = int(sharing_number)
tip_amount = tip_percent / 100 * bill_total
print(f'Tip amount = ${tip_amount:.2f}')
total_amount = bill_total + tip_amount
print(f'Total bill = ${bill_total:.2f}')
tip_per_person = tip_amount / sharing_number
print(f'Tip amount per person = ${tip_per_person:.2f}')
total_per_person = total_amount / sharing_number
print(f'Total amount per person = ${total_per_person:.2f}')
