import turtle
shelly = turtle.Turtle()
shelly.color('green')
shelly.begin_fill()
shelly.circle(100)
shelly.end_fill()
shelly.penup()
shelly.goto(-30, 100)
shelly.pendown()
shelly.begin_fill()
shelly.color('white')
shelly.circle(30)
shelly.end_fill()
shelly.begin_fill()
shelly.color('black')
shelly.circle(20)
shelly.end_fill()
shelly.penup()
shelly.forward(60)
shelly.pendown()
shelly.begin_fill()
shelly.color('white')
shelly.circle(30)
shelly.end_fill()
shelly.begin_fill()
shelly.color('black')
shelly.circle(20)
shelly.end_fill()
shelly.hideturtle()


